distinguish between R and W perms errors

diff --git a/utilities/oc-test b/utilities/oc-test
--- a/utilities/oc-test
+++ b/utilities/oc-test
@@ -17,7 +17,7 @@
 # See usage() for syntax.
 #
 
-VERSION=0.94
+VERSION=0.95
 VERIFY_ONLY=0 # false
 MASTER="$HOSTNAME"
 OC_PREFIX=''
@@ -109,13 +109,12 @@ DESCRIPTION
                192.168.122.133:6788,192.168.122.134
   --ceph-secret64 <base64 value>
              The base-64 encoded secret string generated by running:
-               ceph auth get-key client.admin  , followed by pasting that output
-             to the base64 command:
-               echo -n "<output-from-ceph-auth-get-key>" | base64
+               $ ceph auth get-key client.admin | base64
              If omitted and the rbd test is requested and a provided ceph 
              monitor is reachable via ssh, then this value is calculated by the
-             rbd test and is not required. It is ignore by all tests other than
-             the ceph-rbd tests.
+             rbd test and is not required. The user may be prompted for the 
+             monitor's password. It is ignore by all tests other than the
+             ceph-rbd tests.
   --rbd-image <name>
              The name of the ceph-rbd image. If the rbd pool is not defaulted to
              "rbd" then the pool name is also required in the form of:
@@ -751,7 +750,7 @@ function verify_mount() {
   return 1
 }
 
-# returns 0 if the passed-in pod's container has access the the standard
+# returns 0 if the passed-in pod's container has access to the standard
 # busybox volume (dir). For now "access" is defined as both read and write.
 # Args: $1=pod-name, $2=PASS|FAIL (expected result)
 # Note: this function should only be called after the target pod as been
@@ -759,7 +758,7 @@ function verify_mount() {
 function verify_perms() {
 
   local pod="$1"; local pf=$2
-  local out; local expt_pass; local err; local errcnt=0
+  local out; local expt_pass; local err
 
   # nested function to execute the passed-in command on $pod.
   # Returns 1 on errors.
@@ -788,14 +787,15 @@ function verify_perms() {
   # exeute ls in target pod/container
   err=0
   pod_exec ls $BB_DIR || err=1
-  (( err == expt_pass )) || ((errcnt++)) # no read access to bb dir
+  (( err == expt_pass )) || {
+    echo "ERROR: READ access denied"; return 1; }
 
   # exeute touch in target pod/container
   err=0
   pod_exec touch $BB_DIR/$pod || err=1
-  (( err == expt_pass )) || ((errcnt++)) # no write access to bb dir
+  (( err == expt_pass )) || {
+    echo "ERROR: WRITE access denied"; return 1; }
 
-  (( errcnt != 0 )) && return 1 # 1 or more errors
   return 0
 }
 
@@ -808,7 +808,7 @@ function verify_perms() {
 function verify_new_pod() {
 
   local pod="$1"; local pf="$2"; local mnt_type="$3"
-  local i; local MAX=60 # num tries
+  local i; local MAX=90 # num tries, ceph/rbd is slow to mount!
   local SLEEP=3; local out
 
   echo "... checking pod \"$pod\" ..."
@@ -1862,7 +1862,7 @@ spec:
     - name: rbd-vol1
       mountPath: $BB_DIR
       readOnly: false
-  securityContext:
+  securityContext: #no fsGroup: defined
     privileged: false
   volumes:
   - name: rbd-vol1
