nfs handling of sgids done

diff --git a/utilities/oc-test b/utilities/oc-test
--- a/utilities/oc-test
+++ b/utilities/oc-test
@@ -256,10 +256,33 @@ function parse_cmd() {
   return 0
 }
 
+# returns true (0) if the passed-in id is within (inclusive) the pased-in range.
+#   arg1=test id, arg2=range.
+# Ranges are of the form: <startID>/<count>  or <startID>-<endID>  and
+# a list of ranges are separated by a comma (no spaces).  Eg.
+#   range-1,range-2,...range-N
+# Note: the <startID>/<count> form is converted to a dash range by adding
+#   count-1 to <startID>. Eg. 1000/10  => 1000-1009.
+function id_in_range() {
+
+  local test_id=$1; local range="${2//,/ }" # list
+  local id; local r; local start; local end; local cnt
+
+  for r in ${range[@]}; do
+     if [[ $r == *"/"* ]] ; then # <start>/<count> form
+       start=${r%/*}; cnt=${r#*/}; let end=start+cnt-1
+     else # <start>-<end> form
+       start=${r%-*}; end=${r#*-}
+     fi
+     # test if test_id is within this range
+     (( start <= test_id && test_id <= end )) && return 0 # true
+  done
+
+  return 1 # false
+}
+
 # sets the SGIDs, SUIDs, OS_SGID, OS_SUID and the USE_SGID global variables to
-# the values found in the project definition for the passed-in namespace. Also
-# sets the global VALID_SGID to reflect if the sgid for pods will be within the
-# openshift SGID range.
+# the values found in the project definition for the passed-in namespace. 
 function get_supplemental_ids() {
 
   local ns="$1"
@@ -273,7 +296,16 @@ function get_supplemental_ids() {
   OS_SGID=${SGIDs%/*} # first number in range
   # use either the supplied --sgid= value or the openshift default
   USE_SGID=${TGT_SGID:-$OS_SGID}
-  id_in_range $USE_SGID "$OS_SGID" && VALID_SGID=1 || VALID_SGID=0
+
+  # error out if the target sgid is not w/in the openshift range
+  if ! id_in_range $USE_SGID "$SGIDs" ; then
+    echo "ERROR: target SGID of $USE_SGID is not within the range of supplemental"
+    echo "       group IDs defined for the \"$NS\" project. Openshift's SGID"
+    echo "       range is: $SGIDs. Either supply a different --sgid= value or"
+    echo "       change the 'openshift.io/sa.scc.supplemental-groups' range"
+    echo "       using the \"oc edit ns $NS\" command."
+    return 1
+  fi
 
   # SUIDs:
   ids="$(grep 'openshift.io/sa.scc.uid-range:' <<<"$out")"
@@ -281,34 +313,6 @@ function get_supplemental_ids() {
   OS_SUID=${SUIDs%/*} # first number in range
 
   return 0
-}
-
-# returns true (0) if the passed-in id is within (inclusive) the pased-in range.
-#   arg1=test id, arg2=range.
-# Ranges are of the form: <startID>/<count>  or <startID>-<endID>  and
-# a list of ranges are separated by a comma (no spaces).  Eg.
-#   range-1,range-2,...range-N
-# Note: the <startID>/<count> form is converted to a dash range by adding
-#   count-1 to <startID>. Eg. 1000/10  => 1000-1009.
-function id_in_range() {
-
-  local test_id=$1; local range=(${2//,/ }) # array
-  local id; local r; local start; local end; local cnt
-
-  for r in ${range[@]}; do
-     if [[ $r == *"/"* ]] ; then # <start>/<count> form
-       # convert to <start>-<end> form
-       start=${r%/*}; cnt=${r%*/}
-       let end=start+cnt-1
-       r="$start-$end"
-     fi
-
-     # test if test_id is within this range
-     start=${r%-*}; end=${r%*-}
-     (( start <= test_id && test_id <= end )) && return 0 # true
-  done
-
-  return 1 # false
 }
 
 # convert the passed-in list of potential hostnames to ip addresses.
@@ -401,9 +405,6 @@ function validate_ose_env() {
   echo "   Sup Group IDs : $SGIDs"
   echo " Supplied Sup GID: ${TGT_SGID:-<none>}"
   echo " Pod's Group ID  : $USE_SGID"
-  (( VALID_SGID )) &&
-    echo "   ...is within range" ||
-    echo "   ...is NOT within range and will be rejected"
   echo "==================================="
   echo
 
@@ -555,7 +556,7 @@ function verify_new_pod() {
 function verify_new_pv() {
 
   local pv="$1"
-  local i; local TRIES=5; local SLEEP=3; local out
+  local i; local TRIES=15; local SLEEP=2; local out
 
   echo "... checking PV \"$pv\" ..."
 
@@ -616,7 +617,6 @@ function verify_new_endpoint() {
 }
 
 # run the "general" tests.
-# Note: if the user specified a target SGID it is ignored for these tests.
 function general_test() {
 
   local pod
@@ -631,7 +631,7 @@ END_GENERAL
 
   echo
   echo "----------"
-  echo "General Test 1: busybox, emptyDir, SGID $SGID:"
+  echo "General Test 1: busybox, emptyDir, SGID $USE_SGID:"
 
   pod='general-pod1'
   delete_pod $pod
@@ -649,7 +649,7 @@ spec:
     image: busybox
     command: ["sleep", "60000"]
   securityContext:
-    supplementalGroups: [$SGID]
+    supplementalGroups: [$USE_SGID]
     privileged: false
 END
 
@@ -658,7 +658,7 @@ END
 
   echo
   echo "----------"
-  echo "General Test 2: busybox, hostDir plugin, SGID $SGID:"
+  echo "General Test 2: busybox, hostDir plugin, SGID $USE_SGID:"
 
   pod='general-pod2'
   delete_pod $pod
@@ -679,7 +679,7 @@ spec:
     - name: bb-vol
       mountPath: /usr/share/busybox
   securityContext:
-    supplementalGroups: [$SGID]
+    supplementalGroups: [$USE_SGID]
     privileged: false
   volumes:
   - name: bb-vol
@@ -700,6 +700,7 @@ function nfs_test() {
 
   local pod; local pv; local pvc; local out
   local vol_mount='/opt/nfs'; local vol_perms; local vol_gid
+  local sup_gids=$USE_SGID # may have the nfs vol's gid appended
 
   echo "*** NFS test suite ***"
   echo
@@ -707,69 +708,56 @@ function nfs_test() {
   # get nfs server vol mount perms
   echo "Connecting to $NFS via ssh. You may need to enter a password."
   sleep 1
+  echo
 
-  out="$(ssh $NFS "ls -ld $vol_mount")"
+  out="$(ssh $NFS "ls -ld $vol_mount 2>&1")"
   if (( $? == 0 )) ; then
     out=($out) # array
     vol_perms="${out[0]}"
     vol_gid="${out[3]}"
+    # append vol's sgid to pod's sgid?
+    if id_in_range $vol_gid "$SGIDs" ; then
+      if (( vol_gid != USE_SGID )) ; then # append vol gid to supp gids
+        sup_gids+=",$vol_gid"     
+        echo "Pod's supplemental groups are: $sup_gids"
+      fi
+    else
+      echo "WARN: the NFS volume ${vol_mount}'s GID is NOT within the"
+      echo "      \"$NS\" project's range of group IDs: $SGIDs, and"
+      echo "      cannot be added to the pod's list of group IDs."
+    fi
+
   else
-    echo
     echo "WARN: cannot retrieve permissions on $vol_mount from NFS server"
     echo "      \"$NFS\" via ssh. Be aware of potential permission mismatches"
-    echo "      between openshift groups and the nfs mount directory."
+    echo "      between openshift supplemental groups and the NFS mount"
+    echo "      directory."
     echo
     echo "$out"
-    echo
-    sleep 4
   fi
 
   # show more info for running these tests...
   cat <<END_NFS
 
-    Busybox is run with a volume mounted to the NFS server.
-    Remember to open port 2049 on the NFS server "$NFS". A good test for this
-    is, from the openshift-master, "$MASTER", execute:
+    Busybox is run with a volume mounted to the NFS server: $NFS.
+    Remember to open port 2049 on the NFS server. A good test for this is,
+    from the openshift-master, "$MASTER", execute:
        $ telnet $NFS 2049  # ctrl-c to exit
-    To open port 2049, on the NFS server, execute:
+    To open port 2049 execute (on the NFS server):
        $ iptables -I INPUT 1 -p tcp --dport 2049 -j ACCEPTA
 
-    On the NFS server, edit /etc/exports to include /opt/nfs, eg:
+    Also, on the NFS server, edit /etc/exports to include /opt/nfs, eg:
        /opt/nfs *(rw,sync,no_root_squash)
-
-    The SGID for created pods will be $USE_SGID, which is
-END_NFS
-
-  (( VALID_SGID )) &&
-    echo "    within the openshift range of $SGIDs." ||
-    echo "    NOT within the openshift range of $SGIDs."
-
-  cat <<END_NFS
 
     The group ID for the NFS export directory $vol_mount is:
        ${vol_gid:-<unavailable>}
     and permissions on this directory are:
        ${vol_perms:-<unavailable>}
-END_NFS
-
-  if [[ -n "$vol_gid" ]] ; then
-    if id_in_range $vol_gid "$OS_SGIDs" ; then
-      echo "    Pod's suppl group IDs will match NFS mount's GID so all is good!"
-    else
-      echo "    Pod's suppl group ID won't match NFS mount's GID so pod is expected"
-      echo "    to fail."
-    fi
-  else
-    echo "    NFS mount's GID cannot be retrieved so it's unknown at this time if"
-    echo "     the pod can be created or not."
-  fi
-
-  cat <<END_NFS
 
     To edit the range of supplemental group IDs, on the openshift-master, use:
        $ oc edit ns $NS
     and change the 'openshift.io/sa.scc.supplemental-groups' range to
-    include the NFS group ID for $vol_mount.  Also, use
+    include the NFS group ID for $vol_mount.  Also, use:
        $ oc get ns $NS -o yaml
     to see the values for various IDs in the "$NS" project.
 
@@ -826,7 +814,7 @@ END
 
   echo
   echo "----------"
-  echo "NFS Test 2: busybox, nfs plugin, SGID $sgid:"
+  echo "NFS Test 2: busybox, nfs plugin, SGID $sup_gids:"
 
   pod='nfs-pod2'
   delete_pod $pod
@@ -847,7 +835,7 @@ spec:
     - name: nfs-vol2
       mountPath: /usr/share/busybox
   securityContext:
-    supplementalGroups: [$sgid]
+    supplementalGroups: [$sup_gids]
     privileged: false
   volumes:
   - name: nfs-vol2
@@ -862,7 +850,7 @@ END
 
   echo
   echo "----------"
-  echo "NFS Test 3: busybox, PV, PVC, SGID $sgid:"
+  echo "NFS Test 3: busybox, PV, PVC, SGID $sup_gids:"
 
   # a. create PV
   pv='nfs-pv'
@@ -926,7 +914,7 @@ spec:
     - name: nfs-vol3
       mountPath: /usr/share/busybox
   securityContext:
-    supplementalGroups: [$sgid]
+    supplementalGroups: [$sup_gids]
     privileged: false
   volumes:
   - name: nfs-vol3
@@ -1176,7 +1164,9 @@ function execute_tests() {
 parse_cmd $@ || exit -1
 
 NS="$(get_current_namespace)"
-get_supplemental_ids $NS # sets supplemental group and user IDs as globals
+
+# set supplemental group and user IDs as globals
+get_supplemental_ids $NS || exit 1
 
 echo
 if (( VERIFY_ONLY )) ; then
@@ -1193,6 +1183,6 @@ sleep 2
 
 validate_ose_env || exit 1
 
-(( VERIFY_ONLY )) || execute_tests ${TESTS[@]} || exit 1
+(( ! VERIFY_ONLY )) && execute_tests ${TESTS[@]} || exit 1
 
 exit 0
