initial ceph tests

diff --git a/utilities/oc-test b/utilities/oc-test
--- a/utilities/oc-test
+++ b/utilities/oc-test
@@ -67,15 +67,34 @@ DESCRIPTION
   --nfs-server <hostname|ip>
              NFS server's hostname or ip. Required if performing the nfs tests,
              otherwise ignored.
-  --gluster-nodes <list-of-nodes-comma-separated>
-             A list of 2 or more gluster storage node IP addresses, which
-             become the ose endpoints. Hostnames are converted to IPs using
-             getent, but if DNS or /etc/hosts is not setup correctly it is
-             better to supply IPs. Required if performing the gluster tests,
-             otherwise ignored.
+  --gluster-nodes <node-list>
+             A list of 2 or more gluster storage node IP addresses (comma
+             separator), which become the ose endpoints. Hostnames are converted
+             to IPs using getent, but if DNS or /etc/hosts is not setup
+             correctly it is better to supply IPs. Required if performing the
+             gluster tests, otherwise ignored.
   --gluster-vol <volName>
              The name of an existing gluster/RHS volume. Required if performing
              the gluster tests, otherwise ignored.
+  --rbd-monitor <node>
+             The ceph Monitor node IP address. A hostname is converted to an IP
+             using getent, but if DNS or /etc/hosts is not setup correctly it
+             is better to supply the IP. Required if performing the ceph-rbd
+             tests, otherwise ignored.
+  --ceph-secret64 <base64 value>
+             The base-64 encoded secret string generated by running:
+               ceph auth get-key client.admin  , followed by pasting that output
+             to the base64 command:
+               echo -n "<output-from-ceph-auth-get-key>" | base64
+             If omitted and the rbd test is requested and the provided ceph 
+             monitor is reachable via ssh, then this value is calculated by the
+             rbd test and is not required. It is ignore by all tests other than
+             the ceph-rbd tests.
+  --rbd-image <name>
+             The name of the ceph-rbd image. If the rbd pool is not defaulted to
+             "rbd" then the pool name is also required in the form of:
+               <pool-name>/<image-name>
+             Ignored for all tests other than the ceph-rbd tests.
   --version  Show the version string.
   -q         Suppress all prompts and reduce instructional output.
 
@@ -138,7 +157,7 @@ function parse_cmd() {
 
   local errcnt=0
   local opts='q'
-  local long_opts='version,master:,verify,oc-prefix:,nfs-server:,gluster-nodes:,gluster-vol:,sgid:'
+  local long_opts='version,master:,verify,oc-prefix:,nfs-server:,gluster-nodes:,gluster-vol:,sgid:,rbd-monitor:,ceph-secret64:,rbd-image:'
 
   (( $# == 0 )) && usage && exit -1
 
@@ -188,6 +207,21 @@ function parse_cmd() {
 
         --gluster-vol)
           GLUSTER_VOL="$2"
+          shift 2; continue
+        ;;
+
+        --rbd-monitor)
+          MONITOR="$2"
+          shift 2; continue
+        ;;
+
+        --ceph-secret64)
+          CEPH_SECRET64="$2"
+          shift 2; continue
+        ;;
+
+        --rbd-image)
+          RBD_IMAGE="$2"
           shift 2; continue
         ;;
 
@@ -258,6 +292,12 @@ function parse_cmd() {
     # convert hostnames to IPs, if possible
     GLUSTER_NODES=($(convert_host_to_ip ${GLUSTER_NODES[@]}))
     NUM_ENDPOINTS=${#GLUSTER_NODES[@]}
+  fi
+
+  # --rbd-monitor:
+  if (( RBD_TEST )) ; then
+    # convert hostname to IP, if possible
+    MONITOR="$(convert_host_to_ip $MONITOR)"
   fi
 
   return 0
@@ -534,6 +574,35 @@ function delete_endpoint() {
   return 1
 }
 
+# deletes the passed-in secret.
+function delete_secret() {
+
+  local secret="$1"
+  local i; local err; local out; local TRIES=3; local SLEEP=2
+
+  # delete the target secret
+  echo "... deleting secret \"$secret\" (if it exists)..."
+  ssh -q $MASTER "${OC_PREFIX}oc delete secret $secret >&/dev/null"
+
+  # wait for the delete to complete...
+  for ((i=0; i<$TRIES; i++)); do
+     sleep $SLEEP
+     out="$(ssh $MASTER "${OC_PREFIX}oc get secret $secret 2>&1")"
+     err=$?
+     if (( err != 0 )) && 
+        grep -q " not found" <<<"$out" ; then # expected err
+       return 0
+     fi
+     if (( err != 0 )) ; then # unexpected
+       echo "$out"
+       return 1
+     fi
+  done
+
+  echo -e "ERROR: $TRIES tries attempted to delete secret \"$secret\":\n$out"
+  return 1
+}
+
 # returns 0 if the passed-in pod is running. Echos "oc get pod" output for all
 # errors.
 # $1= pod-name
@@ -620,6 +689,26 @@ function verify_new_endpoint() {
   done
 
   echo -e "ERROR: $(((TRIES*SLEEP))) seconds waiting for endpoints \"$endpt\" to start:\n$out"
+  return 1
+}
+
+# returns 0 if the passed-in secret is running.
+function verify_new_secret() {
+
+  local secret="$1"
+  local i; local TRIES=3; local SLEEP=2; local out
+
+  echo "... checking secret \"$secret\" ..."
+
+  for ((i=0; i<$TRIES; i++)); do
+     sleep $SLEEP
+     out="$(ssh $MASTER "${OC_PREFIX}oc get secret $secret 2>&1")"
+     (( $? != 0 )) && { 
+       echo "$out"; return 1; }
+     grep -q 'Opaque' <<<"$out" && return 0
+  done
+
+  echo -e "ERROR: $(((TRIES*SLEEP))) seconds waiting for secret \"$secret\" to start:\n$out"
   return 1
 }
 
@@ -1142,6 +1231,104 @@ END
 
   verify_new_pod $pod || {
     echo "ERROR: gluster test #3"; return 1; }
+
+  return 0
+}
+
+# run the "ceph-rbd" tests.
+function rbd_test() {
+
+  local pod; local pv; local pvc; local pool; local image; local dmy
+  local secret_name='ceph-secret'
+
+  pool="${RBD_IMAGE%/*}" # pool name is optional
+  [[ "$pool" == "$RBD_IMAGE" ]] && pool='rbd' # not specifie, use default
+  RBD_IMAGE="${RBD_IMAGE#*/}" # remove pool name if present
+
+  if (( ! QUIET )) ; then
+    cat <<END_RBD
+*** Ceph-RBD test suite ***
+
+    The...
+
+- ceph user is hard-coded to be admin
+- filesytem is hard-coded to be ext4
+- rbd create ceph-image -s 1024
+- rbd map ceph-image
+- rbd showmapped
+- ls /dev/rbd*
+- mkfs.ext4 /dev/rbd0
+- ceph auth get-key client.admin
+- echo -n "AQA8QvJVayBPERAAh/Kg0OYZAHOBz7jFpzLqtg==" | base64
+
+END_RBD
+  
+    read -p "Press any key to continue..." -t120 dmy
+  fi
+
+  echo
+  echo "----------"
+  echo "RBD Test 1: baseline: busybox, ceph-rbd plugin:"
+
+  # a. create ceph-secret
+  delete_secret $secret_name
+
+  # if the ceph-secret was not provided and we have ssh access to the monitor
+  # then calculate the ceph-secret here
+  if [[ -z "$CEPH_SECRET64" ]] ; then
+CEPH_SECRET64="AQA8QvJVayBPERAAh/Kg0OYZAHOBz7jFpzLqtg==" ##TEMP!!!!
+    CEPH_SECRET64="$(echo -n "$CEPH_SECRET64" | base64)"
+echo "***CEPH_SECRET64=$CEPH_SECRET64"
+  fi
+
+  cat <<END | ssh $MASTER "${OC_PREFIX}oc create -f -"
+apiVersion: v1
+kind: Secret
+metadata:
+  name: $secret_name
+data:
+  key: $CEPH_SECRET64
+END
+
+  verify_new_secret $secret_name || {
+    echo "ERROR: RBD test #1"; return 1; }
+
+  # b. create the pod
+  pod='rbd-pod1'
+  delete_pod $pod
+
+echo "***secret_name=$secret_name, pool=$pool, RBD_IMAGE=$RBD_IMAGE, MONITOR=$MONITOR"
+  cat <<END | ssh $MASTER "${OC_PREFIX}oc create -f -"
+apiVersion: v1
+kind: Pod
+metadata:
+  name: $pod
+  labels:
+    name: $pod
+spec:
+  containers:
+  - name: $pod
+    image: busybox
+    command: ["sleep", "60000"]
+    volumeMounts:
+    - name: rbd-vol1
+      mountPath: /usr/share/busybox
+  volumes:
+  - name: rbd-vol1
+    rbd: 
+      monitors: 
+      - $MONITOR
+      pool: $pool
+      image: $RBD_IMAGE
+      user: admin
+      secretRef: 
+        name: $secret_name
+      fsType: ext4
+      readOnly: false
+END
+
+  verify_new_pod $pod || {
+    echo "ERROR: RBD test #1"; return 1; }
 
   return 0
 }
