1) --sgids is a list now, 2) added --blokc-gid for block storage tests (becomes fsgroup value)

diff --git a/utilities/oc-test b/utilities/oc-test
--- a/utilities/oc-test
+++ b/utilities/oc-test
@@ -59,10 +59,24 @@ DESCRIPTION
   --oc-prefix <path>
              An optional path prefix appended to all "oc" commands, eg.
              "/root/origin/_output/local/bin/linux/amd64" for local ose builds.
-  --sgid <number>
-             An optional supplemental group ID to be applied to the pods created
-             by various tests. If omitted the default is the first id in the
-             supplemental group ID range defined for the current project. See:
+  --sgids <number-list>
+             An optional list of 0 or more supplemental group IDs (separated by
+             a comma only) to be prepended to the default SGID provided by OSE.
+             This list of GIDs only applies to shared storage tests (gluster,
+             nfs) since this storage type supports multiple users. For block
+             storage (eg. ceph), use the --block-gid option. If --sgids is used,
+             each created pod uses these GIDs in its securityContext spec. If
+             omitted, the default is to use the first id in the supplemental
+             group ID range defined for the current project. See:
+               $ oc get ns <project> -o yaml  # for the various IDs
+  --block-gid <number>
+             An optional supplemental group ID to used as the FSGroup value for
+             the created pod. This GID only applies to block storage tests
+             (ceph). For shared storage (eg. nfs, gluster), use the --sgids
+             option. If --block-gid is specified each created pod uses this GID 
+             in its securityContext spec. If omitted, the default is to use the
+             first id in the supplemental group ID range defined for the
+             current project. See:
                $ oc get ns <project> -o yaml  # for the various IDs
   --nfs-server <hostname|ip>
              NFS server's hostname or ip. Required if performing the nfs tests,
@@ -83,7 +97,7 @@ DESCRIPTION
              /etc/hosts is not setup correctly it is better to supply the IP.
              If the default port of 6789 is not used then :portNum must follow
              all IPs not using the default port.  Required if performing the 
-             ceph-rbd tests, otherwise ignored. Eg:
+             block-rbd tests, otherwise ignored. Eg:
                192.168.122.133:6788,192.168.122.134
   --ceph-secret64 <base64 value>
              The base-64 encoded secret string generated by running:
@@ -161,7 +175,7 @@ function parse_cmd() {
 
   local errcnt=0
   local opts='q'
-  local long_opts='version,master:,verify,oc-prefix:,nfs-server:,gluster-nodes:,gluster-vol:,sgid:,rbd-monitors:,ceph-secret64:,rbd-image:'
+  local long_opts='version,master:,verify,oc-prefix:,nfs-server:,gluster-nodes:,gluster-vol:,sgids:,block-gid:,rbd-monitors:,ceph-secret64:,rbd-image:'
 
   (( $# == 0 )) && usage && exit -1
 
@@ -189,8 +203,13 @@ function parse_cmd() {
           shift 2; continue
         ;;
 
-        --sgid)
-          TGT_SGID="$2"
+        --sgids) # can be a list
+          ARG_SGIDS="$2"
+          shift 2; continue
+        ;;
+
+        --block-gid) # single number
+          ARG_BLK_GID="$2"
           shift 2; continue
         ;;
 
@@ -271,6 +290,9 @@ function parse_cmd() {
     fi
   fi
 
+  # --sgids: can be a list
+  # nothing needed here, just leave it as a string with commas
+
   # --nfs-server:
   if (( NFS_TEST )) ; then
     if [[ -z "$NFS" ]] ; then
@@ -315,15 +337,18 @@ function parse_cmd() {
   return 0
 }
 
-# returns true (0) if the passed-in id is within (inclusive) the pased-in range.
-#   arg1=test-id, arg2=range.
-# Ranges are of the form: <startID>/<count>  or <startID>-<endID>  and
-# a list of ranges are separated by a comma (no spaces).  Eg.
+# returns true (0) if at least one of the passed-in ids are within (inclusive)
+# any of the pased-in range(s).
+#   arg1=test-ids, arg2=range(s).
+# test-ids is a simple list of 1 or more numeric gids separated by only a comma.
+# Ranges are of the form: <startID>/<count> or <startID>-<endID> and a list of
+# ranges are separated by a comma (no spaces). Eg.
 #   range-1,range-2,...range-N
 function id_in_range() {
 
-  local test_id=$1; local range="${2//,/ }" # list
-  local id; local r; local start; local end; local cnt
+  local test_ids=${1//,/ } # list
+  local range="${2//,/ }"  # list
+  local id; local r; local start; local end; local cnt; local ok
 
   for r in ${range[@]}; do
      if [[ $r == *"/"* ]] ; then # <start>/<count> form
@@ -331,15 +356,21 @@ function id_in_range() {
      else # <start>-<end> form
        start=${r%-*}; end=${r#*-}
      fi
-     # test if test_id is within this range
-     (( start <= test_id && test_id <= end )) && return 0 # true
+
+     # test if any test_ids are within this range
+     ok=0 # assume not within range r
+     for id in $test_ids; do
+        (( id >= start && id <= end )) && { ok=1; break; } # in range
+     done
+     (( ok )) && return 0 # a gid is in range r
   done
 
-  return 1 # false
+  return 1 # none of the test_ids are within any of the ranges
 }
 
-# sets the SGIDs, SUIDs, OS_SGID, OS_SUID and the USE_SGID global variables to
-# the values found in the project definition for the passed-in namespace. 
+# sets the SGIDs, SUIDs, OS_SGID, OS_SUID, USE_SGIDS, and USE_BLK_GID global
+# variables to the values found in the project definition for the passed-in
+# namespace. 
 # Note: ID ranges have 2 formats: <start/cnt> or <start>-<end>
 function get_supplemental_ids() {
 
@@ -353,23 +384,34 @@ function get_supplemental_ids() {
   SGIDs="${ids#*: }"  # remove the property name
   id="${SGIDs%%,*}"   # first range
 
+  # get ose default sgid
   if [[ $id == *"/"* ]] ; then # <start>/<count> form
     OS_SGID=${id%/*} # first number in range
   else # <start>-<end> form
     OS_SGID=${id%-*} # first number in range
   fi
 
-  # use either the supplied --sgid= value or the openshift default
-  USE_SGID=${TGT_SGID:-$OS_SGID}
-  # error out if the target sgid is not w/in the openshift range
-  if ! id_in_range $USE_SGID "$SGIDs" ; then
-    echo "ERROR: target SGID of $USE_SGID is not within the range of supplemental"
-    echo "       group IDs defined for the \"$NS\" project. Openshift's SGID"
-    echo "       range is: $SGIDs. Either supply a different --sgid= value or"
-    echo "       change the 'openshift.io/sa.scc.supplemental-groups' range"
-    echo "       using the \"oc edit ns $NS\" command."
-    return 1
+  # for shared storage, prepend the --sgids list, if provided, to the
+  # ose default sgid
+  USE_SGIDS=$OS_SGID # initial value
+  if [[ -n "$ARG_SGIDS" ]] ; then
+    # error if the supplied sgids are not w/in at least 1 of the ose ranges
+    if ! id_in_range $ARG_SGIDS "$SGIDs" ; then
+      echo "ERROR: supplied SGIDs of \"$ARG_SGIDS\" not within the range of"
+      echo "  supplemental group IDs defined for the \"$NS\" project."
+      echo "  Openshift's SGID range is: \"$SGIDs\"."
+      echo "  Either supply a different --sgids= value or change the"
+      echo "  'openshift.io/sa.scc.supplemental-groups' range using:"
+      echo "    $ oc edit ns $NS"
+      return 1
+    fi
+    # ok to prepend the user-supplied sgids to the ose default sgid
+    USE_SGIDS="$ARG_SGIDS,$OS_SGID"
   fi
+
+  # for block storage, use either the ose default gid or the user-supplied
+  # --block-gid number
+  USE_BLK_GID=${ARG_BLK_GID:-$OS_SGID}
 
   # SUIDs:
   ids="$(grep 'openshift.io/sa.scc.uid-range:' <<<"$out")"
@@ -487,17 +529,19 @@ function validate_ose_env() {
   echo "... validated"
   echo
   echo "==================================="
-  echo " Master node     : $MASTER"
-  echo " OSE worker nodes: ${OSE_NODES[@]}"
+  echo " OSE master node      : $MASTER"
+  echo " OSE nodes            : ${OSE_NODES[@]}"
   if (( ${#not_ready_nodes[@]} )) ; then
     echo "  ** these nodes are not scheduable:"
     echo "       ${not_ready_nodes[@]}"
   fi
-  echo " Current project : $NS"
-  echo "   Sup User IDs  : $SUIDs"
-  echo "   Sup Group IDs : $SGIDs"
-  echo " Supplied Sup GID: ${TGT_SGID:-<none>}"
-  echo " Pod's Group ID  : $USE_SGID"
+  echo " Current project      : \"$NS\""
+  echo "   User IDs           : $SUIDs"
+  echo "   Group IDs          : $SGIDs"
+  echo " Supplied Supl GIDs   : ${ARG_SGIDS:-<none>}"
+  echo " Supplied Block GID   : ${ARG_BLK_GID:-<none>}"
+  echo " Shared storage pod's GID: $USE_SGIDS"
+  echo " Blk storage pod's GID: $USE_BLK_GID"
   echo "==================================="
   echo
 
@@ -874,7 +918,7 @@ END_GENERAL
 
   echo
   echo "----------"
-  echo "General Test 1: busybox, emptyDir, SGID $USE_SGID:"
+  echo "General Test 1: busybox, emptyDir, SGIDs: $USE_SGIDS"
 
   pod='general-pod1'
   delete_pod $pod
@@ -892,7 +936,7 @@ spec:
     image: busybox
     command: ["sleep", "60000"]
   securityContext:
-    supplementalGroups: [$USE_SGID]
+    supplementalGroups: [$USE_SGIDS]
     privileged: false
 END
 
@@ -901,7 +945,7 @@ END
 
   echo
   echo "----------"
-  echo "General Test 2: busybox, hostPath plugin, SGID $USE_SGID:"
+  echo "General Test 2: busybox, hostPath plugin, SGIDs: $USE_SGIDS"
 
   pod='general-pod2'
   delete_pod $pod
@@ -922,7 +966,7 @@ spec:
     - name: bb-vol
       mountPath: /usr/share/busybox
   securityContext:
-    supplementalGroups: [$USE_SGID]
+    supplementalGroups: [$USE_SGIDS]
     privileged: false
   volumes:
   - name: bb-vol
@@ -941,7 +985,6 @@ function nfs_test() {
 
   local pod; local pv; local pvc; local out; local ssh_ok
   local vol_mount='/opt/nfs'; local vol_perms; local vol_gid
-  local sup_gids=$USE_SGID # may have the nfs vol's gid appended
 
   echo
   echo "*** NFS test suite ***"
@@ -969,21 +1012,7 @@ function nfs_test() {
     echo "$out"
   fi
 
-  # append nfs vol's sgid to pod's sgid?
-  if [[ -n "$vol_gid" ]] ; then
-    if id_in_range $vol_gid "$SGIDs" ; then
-      if (( vol_gid != USE_SGID )) ; then # append vol gid to supp gids
-        sup_gids+=",$vol_gid"     
-        echo "Pod's supplemental groups are: $sup_gids"
-      fi
-    else
-      echo "WARN: the NFS volume ${vol_mount}'s GID of $vol_gid is NOT within"
-      echo "  the \"$NS\" project's range of group IDs: $SGIDs, and"
-      echo "  thus cannot be added to the pod's list of group IDs."
-    fi
-  fi
-
-  # show more info for running these tests...
+  # show more info about running these tests...
   if (( ! QUIET )) ; then
     cat <<END_NFS
 
@@ -1011,7 +1040,7 @@ function nfs_test() {
 
     On the other hand, if it's ok to change the perms on $vol_mount to match
     openshift's range of groups, then execute (on $NFS):
-       $ chgrp $USE_SGID /opt/nfs
+       $ chgrp $OS_SGID /opt/nfs
 
     Note: it may necessary to restart NFS:
        $ systemctl restart rpcbind nfs
@@ -1023,7 +1052,8 @@ END_NFS
 
   echo
   echo "----------"
-  echo "NFS Test 1: baseline: busybox, nfs plugin:"
+  echo "NFS Test 1: baseline: busybox, nfs plugin"
+  echo "  (no supplementalGroups defined for this pod)"
 
   pod='nfs-pod1'
   delete_pod $pod
@@ -1066,7 +1096,7 @@ END
 
   echo
   echo "----------"
-  echo "NFS Test 2: busybox, nfs plugin, SGID $sup_gids:"
+  echo "NFS Test 2: busybox, nfs plugin, SGIDs: $USE_SGIDS"
 
   pod='nfs-pod2'
   delete_pod $pod
@@ -1087,7 +1117,7 @@ spec:
     - name: nfs-vol2
       mountPath: /usr/share/busybox
   securityContext:
-    supplementalGroups: [$sup_gids]
+    supplementalGroups: [$USE_SGIDS]
     privileged: false
   volumes:
   - name: nfs-vol2
@@ -1105,7 +1135,7 @@ END
 
   echo
   echo "----------"
-  echo "NFS Test 3: busybox, PV, PVC, SGID $sup_gids:"
+  echo "NFS Test 3: busybox, PV, PVC, SGIDs: $USE_SGIDS"
 
   # a. create PV
   pv='nfs-pv'
@@ -1171,7 +1201,7 @@ spec:
     - name: nfs-vol3
       mountPath: /usr/share/busybox
   securityContext:
-    supplementalGroups: [$sup_gids]
+    supplementalGroups: [$USE_SGIDS]
     privileged: false
   volumes:
   - name: nfs-vol3
@@ -1194,7 +1224,6 @@ function gluster_test() {
   local pod; local node; local endpoints=''; local out
   local endpt='gluster-endpoints'; local pv; local pvc
   local mnt_perms; local mnt_gid
-  local sup_gids=$USE_SGID # may have the gluster vol's gid appended
 
   echo
   echo "*** Gluster test suite ***"
@@ -1227,21 +1256,7 @@ function gluster_test() {
     echo "$out"
   fi
 
-  # append mnt's sgid to pod's sgid?
-  if [[ -n "$mnt_gid" ]] ; then
-    if id_in_range $mnt_gid "$SGIDs" ; then
-      if (( mnt_gid != USE_SGID )) ; then # append mount gid to supp gids
-        sup_gids+=",$mnt_gid"     
-        echo "Pod's supplemental groups are: $sup_gids"
-      fi
-    else
-      echo "WARN: the Gluster volume ${GLUSTER_VOL}'s GID of $mnt_gid is NOT"
-      echo "  within the \"$NS\" project's range of group IDs: $SGIDs,"
-      echo "  and thus cannot be added to the pod's list of group IDs."
-    fi
-  fi
-
-  # show more info for running these tests...
+  # show more info about running these tests...
   if (( ! QUIET )) ; then
     cat <<END_GLUSTER
 
@@ -1285,7 +1300,8 @@ END_GLUSTER
 
   echo
   echo "----------"
-  echo "Gluster Test 1: baseline: busybox, glusterfs plugin:"
+  echo "Gluster Test 1: baseline: busybox, glusterfs plugin"
+  echo "  (no supplementalGroups defined for this pod)"
 
   # a. create endpoints
   delete_endpoint $endpt
@@ -1330,6 +1346,8 @@ spec:
     volumeMounts:
     - name: gluster-vol1
       mountPath: /usr/share/busybox
+  securityContext:
+      privileged: false
   volumes:
   - name: gluster-vol1
     glusterfs:
@@ -1346,7 +1364,7 @@ END
 
   echo
   echo "----------"
-  echo "Gluster Test 2: busybox, glusterfs plugin, SGID $sup_gids:"
+  echo "Gluster Test 2: busybox, glusterfs plugin, SGIDs: $USE_SGIDS"
 
   pod='gluster-pod2'
   delete_pod $pod
@@ -1366,7 +1384,7 @@ spec:
     - name: gluster-vol2
       mountPath: /usr/share/busybox
   securityContext:
-    supplementalGroups: [$sup_gids]
+    supplementalGroups: [$USE_SGIDS]
     privileged: false
   volumes:
   - name: gluster-vol2
@@ -1384,7 +1402,7 @@ END
 
   echo
   echo "----------"
-  echo "Gluster Test 3: busybox, PV, PVC, SGID $sup_gids:"
+  echo "Gluster Test 3: busybox, PV, PVC, SGIDs: $USE_SGIDS"
 
   # a. create PV
   pv='gluster-pv'
@@ -1448,7 +1466,7 @@ spec:
     - name: gluster-vol3
       mountPath: /usr/share/busybox
   securityContext:
-    supplementalGroups: [$sup_gids]
+    supplementalGroups: [$USE_SGIDS]
     privileged: false
   volumes:
   - name: gluster-vol3
@@ -1527,7 +1545,8 @@ END_RBD
 
   echo
   echo "----------"
-  echo "RBD Test 1: baseline: busybox, ceph-rbd plugin:"
+  echo "RBD Test 1: baseline: busybox, ceph-rbd plugin"
+  echo "  (no supplementalGroups defined for this pod)"
 
   # a. create ceph-secret
   delete_secret $secret_name
@@ -1569,7 +1588,6 @@ spec:
     - name: rbd-vol1
       mountPath: /usr/share/busybox
   securityContext:
-    #fsGroup: $USE_SGID
     privileged: false
   volumes:
   - name: rbd-vol1
@@ -1593,7 +1611,7 @@ END
 
   echo
   echo "----------"
-  echo "RBD Test 2: busybox, ceph-rbd plugin, PV, PVC, SGID=$USE_SGID:"
+  echo "RBD Test 2: busybox, ceph-rbd plugin, PV, PVC, FSGroup: $USE_BLK_GID"
 
   # a. create pv
   pv='rbd-pv'
@@ -1663,7 +1681,7 @@ spec:
     - name: rbd-vol2
       mountPath: /usr/share/busybox
   securityContext:
-    fsGroup: $USE_SGID
+    fsGroup: $USE_BLK_GID
     privileged: false
   volumes:
   - name: rbd-vol2
